### ISSUE TITLE
Usage.py cannot find csv file.

### ISSUE THREAD

**Issue by soumilbaldota** [aboyher/dash_upsetjs#1]
Usage.py cannot find csv file.

 handle = open( FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/aboyh/Downloads/scopus.csv'

**Comment by aboyher** [comment]
> Usage.py cannot find csv file.
> 
> 
> 
>  handle = open( FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/aboyh/Downloads/scopus.csv'

I must have deleted the file. Sorry, this was for personal use mostly. I believe the data for upsetjs needs to be a list of dicts, dicts having the format {name:[set1, set2,...]}. You should be able to figure it out from here: https://github.com/upsetjs/upsetjs.

**Comment by soumilbaldota** [comment]
> > Usage.py cannot find csv file.
> > handle = open( FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/aboyh/Downloads/scopus.csv'
> 
> I must have deleted the file. Sorry, this was for personal use mostly. I believe the data for upsetjs needs to be a list of dicts, dicts having the format {name:[set1, set2,...]}. You should be able to figure it out from here: https://github.com/upsetjs/upsetjs.

Ok that's fine, thanks though.
